## Ejemplo simplista de **Aprendizaje supervisado**: predecir si algo es *grande* o *pequeño*

---

Imaginemos que la máquina aprende que:

*   si el número es menor que 5 → “pequeño”
*   si es mayor o igual que 5 → “grande”.

si es mayor o igual que 5 → “grande”.

Pero no le decimos la regla directamente, solo ejemplos.

**Qué hace**: Calcula un “límite” y decide si algo es pequeño o grande.

In [4]:
import numpy as np

# Datos de entrenamiento (números)
X = np.array([1, 2, 3, 6, 7, 8])
# Respuestas correctas (0 = pequeño, 1 = grande)
y = np.array([0, 0, 0, 1, 1, 1])

# “Entrenamiento”: encontrar el punto que mejor separa pequeños y grandes

print("Pequeños",X[y == 0])
print("Max de los pequeños ",X[y==0].max())

print("Grandes", X[y == 1])
print("Min de los grandes ",X[y==1].min())
limite = (X[y == 0].max() + X[y == 1].min()) / 2

print("La máquina aprendió que el límite es:", limite)

# Predicción
nuevos = np.array([2, 5, 9])
prediccion = (nuevos >= limite).astype(int)

print("Nuevos números:", nuevos)
print("Predicciones (0=pequeño, 1=grande):", prediccion)

Pequeños [1 2 3]
Max de los pequeños  3
Grandes [6 7 8]
Min de los grandes  6
La máquina aprendió que el límite es: 4.5
Nuevos números: [2 5 9]
Predicciones (0=pequeño, 1=grande): [0 1 1]


## Ejemplo más parecido al **Aprendizaje supervisado** minimizando errores

In [9]:
import numpy as np

# Datos de entrenamiento
X = np.array([1, 2, 3, 6, 7, 8])
y = np.array([0, 0, 0, 1, 1, 1])

# Creamos 100 posibles límites
posibles_limites = np.linspace(X.min(), X.max(), 100)
print("Posibles limites generados automáticamente ", posibles_limites)
# Calculamos las predicciones para todos los límites a la vez
# Esto crea una matriz: filas = datos, columnas = límites

predicciones = (X[:, None] >= posibles_limites[None, :]).astype(int)
print("Predicciones ",predicciones)
# Comparamos con las etiquetas y contamos errores
# predicciones != y[:, None] → True si hay error
print("Respuestas correctas",y[:None])
print("Hay error: ", predicciones != y[:, None])

errores = np.sum(predicciones != y[:, None], axis=0)
print("errores",errores)
# Elegimos el límite con menor error
indice_mejor = np.argmin(errores)
print("El indice del limite con menos errores")
mejor_limite = posibles_limites[indice_mejor]

print("Mejor límite aprendido:", mejor_limite)
print("Errores en entrenamiento:", errores[indice_mejor])

# Predicción con nuevos datos
nuevos = np.array([2, 5, 9])
prediccion = (nuevos >= mejor_limite).astype(int)
print("Predicciones para nuevos números:", prediccion)


Posibles limites generados automáticamente  [1.         1.07070707 1.14141414 1.21212121 1.28282828 1.35353535
 1.42424242 1.49494949 1.56565657 1.63636364 1.70707071 1.77777778
 1.84848485 1.91919192 1.98989899 2.06060606 2.13131313 2.2020202
 2.27272727 2.34343434 2.41414141 2.48484848 2.55555556 2.62626263
 2.6969697  2.76767677 2.83838384 2.90909091 2.97979798 3.05050505
 3.12121212 3.19191919 3.26262626 3.33333333 3.4040404  3.47474747
 3.54545455 3.61616162 3.68686869 3.75757576 3.82828283 3.8989899
 3.96969697 4.04040404 4.11111111 4.18181818 4.25252525 4.32323232
 4.39393939 4.46464646 4.53535354 4.60606061 4.67676768 4.74747475
 4.81818182 4.88888889 4.95959596 5.03030303 5.1010101  5.17171717
 5.24242424 5.31313131 5.38383838 5.45454545 5.52525253 5.5959596
 5.66666667 5.73737374 5.80808081 5.87878788 5.94949495 6.02020202
 6.09090909 6.16161616 6.23232323 6.3030303  6.37373737 6.44444444
 6.51515152 6.58585859 6.65656566 6.72727273 6.7979798  6.86868687
 6.93939394 7.0101010

## Ejemplo de comparación de dos arrays, de diferentes dimensiones

* Numpy dispone de Broadcasting y permite expandir arrays para realizar operaciones con matrices de diferentes tamaños

In [ ]:
M = np.array([[1,2,3], [4,5,6], [7,8,9], [0,1,2], [3,4,5], [6,7,8], [9,0,1]])
v = np.array([2, 4, 7, 0, 3, 6, 8])

comparacion = M >= v[:, None]

print(comparacion)


[[False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False False]]


## Generación de un dataset de dimension (12x4) de ventas por mes para 4 regiones

In [3]:
import numpy as np

# Simula datos de ventas (12 meses, 4 regiones)
ventas = np.random.randint(1000, 5000, size=(12, 4))

print("Shape:", ventas.shape)
print(np.transpose(ventas))
print("Primeras filas:\n", ventas[:5])


Shape: (12, 4)
[[4146 1354 1847 4308 3242 3642 2764 1163 4343 3743 4124 2186]
 [2179 4821 1590 2748 4988 1389 4815 4476 2434 2226 4355 3462]
 [1170 3760 1455 2179 1503 4650 1493 1048 4561 3187 3524 2064]
 [4136 2639 1042 4819 1596 4129 2228 1561 3014 2583 1607 2213]]
Primeras filas:
 [[4146 2179 1170 4136]
 [1354 4821 3760 2639]
 [1847 1590 1455 1042]
 [4308 2748 2179 4819]
 [3242 4988 1503 1596]]
