# Concepto de Correlación

## Generación de datos sintéticos, con Numpy

*  30 muestras
*   Variable horas. Aleatorio entre 0 y 10 horas  
*   Variable ruido. Aleatorio entre 0 y 100 distribuido uniformemente.
*   Variable calificaciones que dependerá de horas de estudio más ruido (3*horas de estudio + ruido)
¿Qué tipo de relación es ésta?
*   Generar matriz de correlación de Pearson



In [1]:
import numpy as np
muestras= 80
np.random.seed(30)
horas = np.random.randint(0,10,muestras)
ruido= np.random.uniform(-10,10,muestras)
calificaciones=3*horas
calificaciones_ruido=3*horas+ruido
print(f"horas\tcalficaciones")

data = np.column_stack([horas, calificaciones,calificaciones_ruido])

print(data)
print (f"Horas-calificaciones")
matriz = np.corrcoef(horas,calificaciones)
print(f"\n{matriz}")
print (f"Horas-calificaciones_ruido")
matriz_ruido = np.corrcoef(horas,calificaciones_ruido)
print(f"\n{matriz_ruido}")


horas	calficaciones
[[ 5.         15.         14.86927386]
 [ 5.         15.          7.8722425 ]
 [ 4.         12.          2.61643783]
 [ 7.         21.         29.78311456]
 [ 2.          6.          1.1367543 ]
 [ 5.         15.          6.14269206]
 [ 1.          3.          0.75416449]
 [ 3.          9.          6.14193495]
 [ 9.         27.         36.72768286]
 [ 7.         21.         29.79181275]
 [ 7.         21.         22.65550447]
 [ 1.          3.         12.86206268]
 [ 1.          3.         12.79829001]
 [ 3.          9.         16.30112748]
 [ 2.          6.         -0.76563543]
 [ 2.          6.          3.36980481]
 [ 4.         12.          8.1345332 ]
 [ 4.         12.          8.81726486]
 [ 6.         18.         13.80955495]
 [ 0.          0.          2.75728146]
 [ 6.         18.          9.01308006]
 [ 0.          0.          8.70368621]
 [ 7.         21.         11.51689674]
 [ 4.         12.         12.63278104]
 [ 2.          6.         -2.56792411]
 [ 1.

Dado un dataset con columnas numericas, calcular el grado de correlación entre las columnas y eliminar las columnas que tengan un grado de correlación superior a 0.90
Crear un dataset de 3x6.




In [10]:
import numpy as np

np.random.seed(0)

rows = 25

col1 = np.random.randn(rows)
col2 = col1 * 0.8 + np.random.randn(rows) * 0.2      # correlación alta
col3 = np.random.randn(rows)                         # poca correlación
col4 = col1 * 0.95 + np.random.randn(rows) * 0.05    # correlación muy alta
col5 = 0.5 * col1 + 0.5 * col3                        # correlación mixta

data = np.column_stack([col1, col2, col3, col4, col5])

print("Dataset sintético (primeras filas):")
print(data[:5])

matriz =np.corrcoef(data,rowvar=False)
mask_correlacion_superior_0_90=np.abs(matriz)>0.90
print(mask_correlacion_superior_0_90)

np.fill_diagonal(mask_correlacion_superior_0_90,False) # ignoramos la diagonal

# 3. Detectar columnas a eliminar
n_cols = mask_correlacion_superior_0_90.shape[0]
cols_a_eliminar = np.zeros(n_cols, dtype=bool)

for i in range(n_cols):
    if not cols_a_eliminar[i]:
        # Si la columna i tiene correlación alta con otra columna j
        correlated = mask_correlacion_superior_0_90[i] & (~cols_a_eliminar)  # ignorar ya eliminadas
        # Eliminamos todas las columnas correlacionadas j > i
        cols_a_eliminar = cols_a_eliminar | correlated

# 4. Crear dataset reducido
data_reducido = data[:, ~cols_a_eliminar]

print("Columnas a eliminar (boolean mask):", cols_a_eliminar)
print("\nDataset reducido (primeras filas):")
print(data_reducido[:5])

Dataset sintético (primeras filas):
[[ 1.76405235  1.12036874 -0.89546656  1.64160922  0.43429289]
 [ 0.40015721  0.32927747  0.3869025   0.33660949  0.39352985]
 [ 0.97873798  0.74555362 -0.51080514  0.9008586   0.23396642]
 [ 2.2408932   2.0992704  -1.18063218  2.11327091  0.53013051]
 [ 1.86755799  1.78791815 -0.02818223  1.77698836  0.91968788]]
[[ True  True False  True False]
 [ True  True False  True False]
 [False False  True False False]
 [ True  True False  True False]
 [False False False False  True]]
Columnas a eliminar (boolean mask): [False  True False  True False]

Dataset reducido (primeras filas):
[[ 1.76405235 -0.89546656  0.43429289]
 [ 0.40015721  0.3869025   0.39352985]
 [ 0.97873798 -0.51080514  0.23396642]
 [ 2.2408932  -1.18063218  0.53013051]
 [ 1.86755799 -0.02818223  0.91968788]]


Dado un dataset, dividir en 20% para entrenamiento y un 80 para predicción

In [3]:
import numpy as np

# Dataset de ejemplo
np.random.seed(0)
data = np.random.randn(25, 5)

# Proporciones
train_frac = 0.2
train_size = int(data.shape[0] * train_frac)

# Seleccionar índices de entrenamiento aleatoriamente, sin repetición
train_idx = np.random.choice(data.shape[0], size=train_size, replace=False)

# Crear máscara booleana para identificar filas de entrenamiento
mask = np.zeros(data.shape[0], dtype=bool)
mask[train_idx] = True

# Índices de test son los que no están en entrenamiento
test_idx = np.where(~mask)[0]

# Crear splits
train_data = data[train_idx]
test_data = data[test_idx]

# Mostrar resultados
print("Indices de entrenamiento:", train_idx)
print("Indices de predicción:", test_idx)

print("\nDatos de entrenamiento:\n", train_data)
print("\nDatos de predicción:\n", test_data)




Indices de entrenamiento: [ 6  8  4 20 19]
Indices de predicción: [ 0  1  2  3  5  7  9 10 11 12 13 14 15 16 17 18 21 22 23 24]

Datos de entrenamiento:
 [[ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [ 1.8831507  -1.34775906 -1.270485    0.96939671 -1.17312341]
 [ 0.70657317  0.01050002  1.78587049  0.12691209  0.40198936]]

Datos de predicción:
 [[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]
 [-0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223]
 [ 

Averiguar si un dataset tiene filas repetidas y si es así eliminar dejando únicamente una.


In [4]:
import numpy as np
# 1. Crear un dataset con filas duplicadas
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],   # duplicada
    [7, 8, 9],
    [4, 5, 6],   # duplicada
    [10, 11, 12]
])

print("Dataset original:")
print(data)

# 2. Detectar y eliminar filas duplicadas
# np.unique con axis=0 devuelve solo filas únicas
unique_rows = np.unique(data, axis=0)

print("\nDataset sin filas duplicadas:")
print(unique_rows)


Dataset original:
[[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]

Dataset sin filas duplicadas:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],   # duplicada
    [7, 8, 9],
    [4, 5, 6],   # duplicada
    [1, 2, 3]    # duplicada
])

# Obtener información de unicidad
unique_rows, first_idx, inv, counts = np.unique(
    data, axis=0,
    return_index=True,
    return_inverse=True,
    return_counts=True
)


# Lista donde guardaremos los índices duplicados
duplicate_indices = []

# Para cada fila única, detectar todas sus apariciones
for i, c in enumerate(counts):
    if c > 1:  # si aparece más de una vez
        # posiciones donde aparece esta fila
        all_occ = np.where(inv == i)[0]
        # agregar todas excepto la primera
        duplicate_indices.extend(all_occ[1:])

print("Índices de filas duplicadas:", duplicate_indices)


Índices de filas duplicadas: [np.int64(2), np.int64(5), np.int64(4)]
